Exploratory data analysis with Pandas (Bike-sharing dataset)

This dataset contains daily bike rental records from a bike-sharing system. It includes information about date, season, weather conditions, and user counts, allowing analysis of how environmental and temporal factors affect bike usage.

Main Columns:

instant – record index

dteday – date of record

season – 1: spring, 2: summer, 3: fall, 4: winter

yr – year (0: 2011, 1: 2012)

mnth – month (1–12)

holiday – 1 if day is a holiday

weekday – day of the week

workingday – 1 if not weekend/holiday

weathersit – weather category (1 = good till 4 = severe)

temp – normalized temperature

atemp – normalized “feels like” temperature

hum – normalized humidity

windspeed – normalized wind speed

casual – number of casual users

registered – number of registered users

cnt – total rentals (target variable)

In [8]:
import numpy as np
import pandas as pd

pd.set_option("display.max.columns", 100)

data = pd.read_csv("M:/accenture/ds-ml-training/ds-ai-assignments-maksym-bondar/weeks/week1/data/day.csv")  
data.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [3]:
data.shape

(731, 16)

In [4]:
data.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [5]:
(data == "").sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [6]:
data.describe(include="all")

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,731.000000,731,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000
unique,NaN,731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,2011-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,366.000000,NaN,2.496580,0.500684,6.519836,0.028728,2.997264,0.683995,1.395349,0.495385,0.474354,0.627894,0.190486,848.176471,3656.172367,4504.348837
std,211.165812,NaN,1.110807,0.500342,3.451913,0.167155,2.004787,0.465233,0.544894,0.183051,0.162961,0.142429,0.077498,686.622488,1560.256377,1937.211452
min,1.000000,NaN,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.059130,0.079070,0.000000,0.022392,2.000000,20.000000,22.000000
25%,183.500000,NaN,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,0.337083,0.337842,0.520000,0.134950,315.500000,2497.000000,3152.000000
50%,366.000000,NaN,3.000000,1.000000,7.000000,0.000000,3.000000,1.000000,1.000000,0.498333,0.486733,0.626667,0.180975,713.000000,3662.000000,4548.000000
75%,548.500000,NaN,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,0.655417,0.608602,0.730209,0.233214,1096.000000,4776.500000,5956.000000
max,731.000000,NaN,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,0.861667,0.840896,0.972500,0.507463,3410.000000,6946.000000,8714.000000

In [7]:
data.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   dteday      731 non-null    object
 2   season      731 non-null    int64
 3   yr          731 non-null    int64
 4   mnth        731 non-null    int64
 5   holiday     731 non-null    int64
 6   weekday     731 non-null    int64
 7   workingday  731 non-null    int64
 8   weathersit  731 non-null    int64
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  casual      731 non-null    int64
 14  registered  731 non-null    int64
 15  cnt         731 non-null    int64
 16  demand      731 non-null    object
dtypes: float64(4), int64(11), object(2)
memory usage: 97.2+ KB

1. Count how many working days and non-working days exist in the dataset.

In [10]:
data["workingday"].value_counts()

workingday
1    500
0    231
Name: count, dtype: int64

2. Average rentals on working vs non-working days

In [11]:
avg_working = data[data["workingday"] == 1]["cnt"].mean()
avg_nonworking = data[data["workingday"] == 0]["cnt"].mean()

avg_working, avg_nonworking

(np.float64(4584.82), np.float64(4330.168831168831))

3. Proportion of bad-weather days

In [12]:
bad_weather_prop = (data["weathersit"] == 3).sum() / data.shape[0] # let's assume weathersit == 3 is bad
bad_weather_prop

np.float64(0.028727770177838577)

In [13]:
bad_weather_prop = data[data["weathersit"].isin([3, 4])].shape[0] / data.shape[0]
bad_weather_prop

0.028727770177838577

4–5. Mean & std of rentals on high- vs low-demand days

In [14]:
threshold = data["cnt"].median()

high = data[data["cnt"] > threshold]["cnt"]
low  = data[data["cnt"] <= threshold]["cnt"]

print("High demand mean:", round(high.mean(), 2))
print("High demand std:", round(high.std(), 2))

print("Low demand mean:", round(low.mean(), 2))
print("Low demand std:", round(low.std(), 2))

High demand mean: 6087.91
High demand std: 1092.55
Low demand mean: 2925.11
Low demand std: 1143.11

6. Are high-demand days only in specific seasons?

In [15]:
high_seasons = data[data["cnt"] > threshold]["season"].unique()
high_seasons

array([2, 3, 4, 1])

all four seasons appear among the high-demand days

In [16]:
season_map = {1: "winter", 2: "spring", 3: "summer", 4: "fall"}
[pd.Series(high_seasons).map(season_map)]

[0    spring
 1    summer
 2      fall
 3    winter
 dtype: object]

7. Rental stats for each season × workingday

In [17]:
for (season, working), sub_df in data.groupby(["season", "workingday"]):
    print(f"Season: {season}, workingday: {working}")
    print(sub_df["cnt"].describe())
    print()

Season: 1, workingday: 0
count      61.000000
mean     2257.098361
std      1371.328926
min       605.000000
25%      1204.000000
50%      1969.000000
75%      2832.000000
max      7836.000000
Name: cnt, dtype: float64

Season: 1, workingday: 1
count     120.000000
mean     2780.541667
std      1386.784655
min       431.000000
25%      1639.000000
50%      2399.500000
75%      3795.500000
max      6312.000000
Name: cnt, dtype: float64

Season: 2, workingday: 0
count      56.000000
mean     5142.428571
std      1822.913301
min       795.000000
25%      4082.500000
50%      5057.500000
75%      6592.750000
max      8294.000000
Name: cnt, dtype: float64

Season: 2, workingday: 1
count     128.000000
mean     4926.664062
std      1640.507634
min      1471.000000
25%      3980.000000
50%      4877.500000
75%      6243.000000
max      8362.000000
Name: cnt, dtype: float64

Season: 3, workingday: 0
count      57.000000
mean     5474.666667
std      1433.686125
min      1115.000000
25%      4484.000000
50%      5305.000000
75%      6299.000000
max      8714.000000
Name: cnt, dtype: float64

Season: 3, workingday: 1
count     131.000000
mean     5718.114504
std      1470.323646
min      1842.000000
25%      4615.500000
50%      5515.000000
75%      7108.500000
max      8173.000000
Name: cnt, dtype: float64

Season: 4, workingday: 0
count      57.000000
mean     4606.210526
std      1791.763943
min       627.000000
25%      3331.000000
50%      4459.000000
75%      5511.000000
max      8555.000000
Name: cnt, dtype: float64

Season: 4, workingday: 1
count     121.000000
mean     4785.611570
std      1658.985666
min        22.000000
25%      3740.000000
50%      4639.000000
75%      5668.000000
max      8156.000000
Name: cnt, dtype: float64

8. Which group has more high-demand days?

In [18]:
high_working = (
    data[(data["workingday"] == 1) & (data["cnt"] > threshold)].shape[0] /
    data[data["workingday"] == 1].shape[0]
)

high_nonworking = (
    data[(data["workingday"] == 0) & (data["cnt"] > threshold)].shape[0] /
    data[data["workingday"] == 0].shape[0]
)

high_working, high_nonworking

(0.512, 0.47186147186147187)

9. Maximum number of rentals + count of such days + workingday share

In [19]:
max_cnt = data["cnt"].max()
max_cnt

np.int64(8714)

How many such days?

In [23]:
n_days_max = data[data["cnt"] == max_cnt].shape[0]
n_days_max

1

What % are working days?

In [24]:
working_share = (
    data[(data["cnt"] == max_cnt) & (data["workingday"] == 1)].shape[0]
    / n_days_max
)

working_share

0.0

In [25]:
data[data["cnt"] == max_cnt]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
623,624,2012-09-15,3,1,9,0,6,0,1,0.608333,0.585867,0.501667,0.247521,3160,5554,8714

10. Average rentals (cnt) for high vs low demand by season

In [26]:
data["demand"] = np.where(data["cnt"] > threshold, "high", "low")

In [27]:
data.groupby(["season", "demand"])["cnt"].mean()

season  demand
1       high      5550.312500
        low       2318.442424
2       high      6068.504425
        low       3279.549296
3       high      6201.678322
        low       3873.088889
4       high      6029.043011
        low       3304.847059
Name: cnt, dtype: float64

In [31]:
pd.crosstab(
    data["season"],
    data["demand"],
    values=data["cnt"],
    aggfunc="mean"
).T

season            1            2            3            4
demand
high    5550.312500  6068.504425  6201.678322  6029.043011
low     2318.442424  3279.549296  3873.088889  3304.847059